### ISSUE TITLE
Toilette kaufen

### ISSUE THREAD

**Issue by krlwlfrt** [krlwlfrt/schrebergarten#13]

**Comment by meikimeik** [comment]
# Eine Möglichkeit:
**Häuschen**: https://www.ebay.de/itm/28mm-Toilettenhaus-160x160-cm-Campingtoilette-Toilette-Gartenhaus-Holzhaus-/122847815619 (659 €)
**Toilette**: http://www.oecobuy.de/shop/Gartentoilette-Gartentoiletten/Biolan-Komplet-Trockentoilette-Gartentoilette-Komposttoilette-120l (428 €)

**Comment by meikimeik** [comment]
Laden in Berlin: 

https://humustoiletten.de/shop01/

Eisenacher Strasse 84 
10781 Berlin

**Comment by krlwlfrt** [comment]
Done
