### ISSUE TITLE
Bienenschwarm besorgen

### ISSUE THREAD

**Issue by krlwlfrt** [krlwlfrt/schrebergarten#2]

**Comment by anselmstordeur** [comment]
Das wäre meine derzeitige Wahl: https://bienenzucht-profi.de/kunstschwaerme/18/buckfast-kunstschwarm/paketbienen-kaufen-standbegattet?c=7

**Comment by krlwlfrt** [comment]
Ist im Grunde auf dem Weg... Status?

**Comment by krlwlfrt** [comment]
Da fehlt ein Komma.

**Comment by anselmstordeur** [comment]
Nächsten Dienstag sollen die Bienen kommen. @meikimeik

**Comment by anselmstordeur** [comment]
Am Montag werde ich die neue Beute aufstellen. 

Plan für Dienstag: Von 8-12 sollen die Bienen bei mir eintreffen. Ich werde eine Umverpackung für den Transport vorbereiten, sodass ich sie halbwegs ruckelfrei und dunkel mit der U-Bahn transportieren kann. Transport mit verpacken dauert eine gute Stunde.

Irgendwann zwischen 9-13 sollte ich also im Garten sein. Die Beute ist dann schon soweit vorbereitet, dass ich die Bienen gleich einsetzen kann. Ich würde Sie nur 15 min vorher stehen lassen, damit sich die Bienen wieder beruhigen. Dann kann ich die Bienen einschlagen. Das heißt:

- Bienen anfeuchten mit Wasserzerstäuber
- Transportbox aufschneiden
- Transportbox auf die Beute schlagen. Dann sollten alle Bienen drin sein.
- Rähmchen draufsetzen
- Pheromon (künstliche Königin) einhängen
- Futterglas oder Futterbox reinstellen
- Beute verschließen
- **Wichtig: Nach einer Stunde nachsehen, wo sie ansetzen zum Bauen**

Plan für Donnerstag Morgen:
- Flugloch öffnen
- Pheromon rausnehmen und luftdicht verpacken
- Königinnenkäfig einsetzen
- Nach ca. 12 std. (Bienen haben sich an den Geruch der Königin gewöhnt): Das Plastikröhrchen am Königinnenkäfig öffnen, damit sich die Arbeiterinnen zur Königin durchfressen können. [Hier](https://www.youtube.com/watch?v=qXVVOn5uZCY) ist das Youtube Video das zeigt, wie es aussieht, wenn die Königin nicht akzeptiert wird.

Ich werde in die ersten 5-10 Rähmchen Mittelwände einlöten. Das spricht zwar gegen Demeter, aber das Volk hat nicht mehr viel Zeit sich auf den Winter vorzubereiten und Wachsplatten verhindern Drohnenbrut und vielleicht auf die Kommunikation über Vibrationen. Das verhindern von Drohnenbrut ist ganz gut für die Volksentwicklung, aber nicht gut für die Entwicklung von einem breiterem Genpool für alle Bienen. [Mehr dazu](https://www.mellifera.de/blog/freibeuter/varroatoleranz-bei-frei-nistenden-honigbienen.html) unter Bedeutung von Drohnenbrut.

Demeter erlaubt nur Mittelwände aus Bienenwachs das in Demeterhaltung gewonnen wurde. Und auch nur im Honigraum. Meine Mittelwände kommen aus konventioneller Haltung. Ich denke das ist in Ordnung, da Drohnenbrut sowieso eher auf äusseren Rähmchen passiert und ich da auf jeden Fall Naturwabenbau haben möchte.

Falls es euch interessiert: [Demeter Richtlinien für Imkerei](https://www.demeter.de/sites/default/files/richtlinien/richtlinien_bienenhaltung_gesamt.pdf)

**Comment by krlwlfrt** [comment]
Alter... Das Video ist ja total verrückt :D, wie der Typ da auch die ganze Zeit reingrabbelt ohne Handschuhe... Bienen sind wohl doch nicht so gefährlich :)

**Comment by krlwlfrt** [comment]
Bei den Entscheidungen vertrauen wir dir einfach... Haben ja eh keine Ahnung.

**Comment by anselmstordeur** [comment]
Die Bienchen haben halt zu tun. Die mögen ihre Königin nicht.

Ich habe gerade die Versandbenachrichtung erhalten. Die Bienen kommen wahrscheinlich gleichzeitig mit der Königin und ohne Pheromon. Dann kommt Dienstag also die Königin mit rein und Donnerstag mach ich auf.

**Comment by krlwlfrt** [comment]
Umso besser! :)
