### ISSUE TITLE
Imkerzeug in den Schrebergarten bringen

### ISSUE THREAD

**Issue by krlwlfrt** [krlwlfrt/schrebergarten#4]

**Comment by anselmstordeur** [comment]
Ich fahre morgen mit Beute im RE nach Berlin. Sie muss dann noch mindestens 3 mal gestrichen werden. Also wäre es ganz gut, wenn wir bald mal #5 anfangen.

**Comment by anselmstordeur** [comment]
Ich habe noch ein paar Sachen die wir mitnehmen sollten, wenn möglich:

- [ ] Beute
- [ ] Rähmchen (Abstandshalter montieren, teilweise drahten)
- [ ] Trennschied
- [ ] Wachsplatten, Drähte, Ösen, Spannägel, Bohrer für Ösen
- [ ] Dämmplatte (MDF oder Hanffaser)
- [ ] Varroa-Gitter
- [ ] Stockermeißel
- [ ] Hut
- [ ] Weiße Lange Klamotten
- [ ] Handschuhe
- [ ] Smoker
- [ ] Wasserzerstäuber
- [ ] Abkehrbesen
- [ ] Zange (zum Drahtspannen)
- [ ] Luftdichte Eimer mindestens 3x 5l

Beute ist heute zum dritten mal gestrichen. An der Beute muss noch gemacht werden:
- [ ] Flugloch schneiden (dafür brauche ich noch ein 48er Sägeblatt für die Kreissäge)
- [ ] Dachblech kaufen und montieren. Vielleicht auch Dachpappe...
- [ ] Rähmchendecke zuschneiden/festtackern

Sollte machbar sein heute. Dann kann die Beute morgen rüber

Die Beute solle noch einmal nach ein oder zwei Monaten besichtig (auf Wetterfestigkeit) und gestrichen werden.

Längerfristig brauchen wir außerdem:
- [ ] Mehr Rähmchen (Cyrill hat neue Schießer, brauchen wir nur noch die Tischkreissäge in der Halle)
- [ ] Ablegertransportkiste
- [ ] Mehr Beuten für Moor und falls man mal über einen Bienenschwarm und Stellplatz stolpert

Mir fällt bestimmt noch was ein... @krlwlfrt kreuz doch mal bitte an, was ihr schon habt.

**Comment by anselmstordeur** [comment]
- [ ] Rähmchenkeil

**Comment by anselmstordeur** [comment]
-[] Gurkenglas

**Comment by krlwlfrt** [comment]
Handschuhe habe ich quasi auch ... Aber sicherlich nicht was du dir vorstellst?!

**Comment by anselmstordeur** [comment]
Nee sicherlich nicht. Aber Zange ist schonmal gut. Hast du einen Hammer da?

**Comment by anselmstordeur** [comment]
Etwas natürliches Brennholz (Zweige, Holzstückchen, Kiefernadeln), Papier und Feuerzeug in einem Eimer für den Smoker.

Das beste wäre, wenn ich noch eine Küchenwaage (bis 5kg) kaufen würde um die einzelnen Rähmchen zu wiegen. Dann kann man super messen, wie schnell das Volk wächst.

Ich würde sowieso eine komplette Werkzeugkiste immer im Garten lassen. Kann ich die dann irgendwo trocken unterstellen, wenn ich nur ein Schlüssel zum Tor bekomme?

Ich überlege übrigens gerade wieder Bienen vom Züchter zu kaufen. (ca. 200€) Letzendlich bin ich mit dem Ablauf bei denen vertraut und reinrassige Bienen sind ne tolle Sache.

**Comment by anselmstordeur** [comment]
Wir brauchen eine Bienentränke. Das ist ein großes Wassergefäß mit flachem Ufer, damit Bienen dort trinken können, aber nicht ertrinken.

Außerdem muss ich nächstes mal die Lochsäge mitbringen und drei Lüftungslöcher in die Beute bohren. Ich brauche dafür noch drei Weinkorken. Ihr trinkt doch bestimmt Wein?

**Comment by krlwlfrt** [comment]
Ja... Aber nicht regelmäßig, @meikimeik.

Bienentränke? Dediziert? Oder Zweckentfremdung? Oder selbst gebaut?

**Comment by krlwlfrt** [comment]
Ist das noch aktuell?

**Comment by anselmstordeur** [comment]
Ich muss morgen an folgendes Denken: 
- [ ] Gurkenglas
- [ ] Werkzeuge (wie oben aufgelistet)
- [ ] Zwei Waagen. Einmal für Beute einmal für Rähmchen
- [ ] Dämmplatte
- [ ] Luftdichte Eimer
- [ ] Mörtelkasten 65l
